---
abstract: 'tag your Moose attributes'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.004, CPAN::Meta::Converter version 2.120921'
keywords: []
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-AttributeTags
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
provides:
  MooseX::AttributeTags:
    file: lib/MooseX/AttributeTags.pm
    version: 0.001
  MooseX::AttributeTags::PRole:
    file: lib/MooseX/AttributeTags/PRole.pm
    version: 0.001
requires:
  Data::OptList: 0
  Moose: 2.0600
  MooseX::Role::Parameterized: 0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-AttributeTags
  homepage: https://metacpan.org/release/MooseX-AttributeTags
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moosex-attributetags
version: 0.001
x_provides_scripts: {}
