---
abstract: 'tag your Moose attributes'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: '0.007'
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-AttributeTags
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  MooseX::AttributeTags:
    file: lib/MooseX/AttributeTags.pm
    version: '0.002'
  MooseX::AttributeTags::PRole:
    file: lib/MooseX/AttributeTags/PRole.pm
    version: '0.002'
requires:
  Data::OptList: '0'
  Moose: '2.0600'
  MooseX::Role::Parameterized: '0'
  perl: '5.008000'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/MooseX-AttributeTags/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-AttributeTags
  homepage: https://metacpan.org/release/MooseX-AttributeTags
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-moosex-attributetags.git
version: '0.002'
